// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBFyXdP0FM04Lvlh2e4xzWtRW4Ohc2HQoE',
    appId: '1:132658384647:web:c45954e8e2f8d9f0373fa2',
    messagingSenderId: '132658384647',
    projectId: 'whatsapp-with-provider',
    authDomain: 'whatsapp-with-provider.firebaseapp.com',
    storageBucket: 'whatsapp-with-provider.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD7FBMzazK5frcdvqshQtkF1wtrhBBquKE',
    appId: '1:132658384647:android:4580e1d8b2fd7dc5373fa2',
    messagingSenderId: '132658384647',
    projectId: 'whatsapp-with-provider',
    storageBucket: 'whatsapp-with-provider.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDTEd_RNj4QqDsJMcKYx8kl16qDUUGzUOs',
    appId: '1:132658384647:ios:45a2958adc8e952f373fa2',
    messagingSenderId: '132658384647',
    projectId: 'whatsapp-with-provider',
    storageBucket: 'whatsapp-with-provider.appspot.com',
    iosClientId: '132658384647-09gsrpss7u2l621kbmetmc7j811t0l7r.apps.googleusercontent.com',
    iosBundleId: 'com.example.whatsapp',
  );
}
